### ISSUE TITLE
'inline: true' displays datepicker on every page

### ISSUE THREAD

**Issue by rgbskills** [crsten/datepickk#10]
I have the following config:

```
var datepicker = new Datepickk({
  // range: true,
  container: document.getElementById('calendar'),
  inline: true
}
```

And the datepicker shows up on other pages where there is no div with id 'calendar', am I doing something wrong or is this a bug?

**Comment by crsten** [comment]
Could you provide an example? 
It's a bit hard to figure it out based on the information in your comment

**Comment by rgbskills** [comment]
I apologize for opening this ticket, it was a turbolinks issue in Rails. Sorry :(
