### ISSUE TITLE
How do I set the starting day to be Monday instead of Sunday. 

### ISSUE THREAD

**Issue by rgbskills** [crsten/datepickk#11]
Hello, I would like to start the week with Monday do I have a way to set this?

Thank You :)

**Comment by crsten** [comment]
Hi, that depends on the language at the moment. What language do you speek?

**Comment by rgbskills** [comment]
The problem is that The application I am building is an english speaking application and it will probably never be translated at least I am not planing to. So I need the calendar to stay english but the start of the week to be Monday.

**Comment by crsten** [comment]
Hmm i see, i will mark this issue as an improvement and fix it asap

**Comment by rgbskills** [comment]
Thank you, this will be a good feature because in the future I would like the user to be able to select the day that the week start with. I bet many others that use this datepicker will also want that.

**Comment by crsten** [comment]
This feature has been released in [1.2.0](https://github.com/crsten/datepickk/releases/tag/v1.2.0)

**Comment by rgbskills** [comment]
Awesomenessss :)
