### ISSUE TITLE
Dates get returned twice

### ISSUE THREAD

**Issue by rgbskills** [crsten/datepickk#13]
Hello, I have a calendar that send's some date params and they get sent twice, Any idea about what I am doing wrong?

here is an example, you will see the duplication in the console after the second selection, For some reason the first time you select its not duplicated.

http://codepen.io/rgbskills/pen/RKXqEa?editors=0010

Thank you very much in advance :)

**Comment by crsten** [comment]
Hi again :) 

It seems to be this line
`datepicker.maxSelections = 7;`

i guess this modification calls the onSelect method which seems to be a bug!
Will look at it asap...

In the meantime you can just avoid setting maxSelections since it isn't necessary anyways

**Comment by crsten** [comment]
#14
