### ISSUE TITLE
Block all past days

### ISSUE THREAD

**Issue by JulianSteinmann** [crsten/datepickk#27]
Hey there all

Thanks a lot for this script, i'm really loving it! 

The only thing that I'm missing is a feature that easily blocks all already past days – I guess that would be something many people will need for various booking-calendar features. (eventually it already does exist and I missed it?)

I did for myself a pretty ugly workaround. – I'm a graphic designer don't judge me =).
My script blocks basicly the last 31 Days which is good enough for me at the moment, but it would be awesome if someone would come up with a smarter & cleaner version of this.

    var B = new Array();
    var currentDate = new Date();
    currentDate.setDate(currentDate.getDate() - 31);

    var yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);

    while (currentDate <= yesterday) {
        B.push(new Date(currentDate));
        currentDate.setDate(currentDate.getDate() + 1);
    }
    datepicker.disabledDates = [B[0], B[1], B[2], B[3], B[4], B[5], B[6], B[7], B[8], B[9], B[10], B[11], B[12], B[13], B[14], B[15], B[16], B[17], B[18], B[19], B[20], B[21], B[22], B[23], B[24], B[25], B[26], B[27], B[28], B[29], B[30] ];

**Comment by crsten** [comment]
Hi there :)

Thanks for your feedback, there is actually already a property for this. It is called minDate and it disables all dates before this date, and there is also a counterpart, maxDate

Hope this helps!

**Comment by JulianSteinmann** [comment]
Hey Crsten

Thanks a lot for the advice. I actually found it already myself before I saw this mail. Silly me, it's even right at the top of the documentation. =S
