### ISSUE TITLE
retrieve selected date on button click

### ISSUE THREAD

**Issue by gvipin92** [crsten/datepickk#30]
Hi,

I wish to retrieve selected date range on button click , please help me as i am new with js.

**Comment by crsten** [comment]
Hi there,

I'm not sure if you're trying to get the dates on some custom buttons or on confirm. 
Anyways i will explain both:


To retrieve from anywhere in your application:
```js
let datepicker = new Datepickk();
let dates  = datepicker.selectedDates //you could do this from anywhere in your code
``` 

To retrive on confirm (part of datepickk):
```js
let datepicker = new Datepickk();
datepicker.onConfirm = function(){
  //this.selectedDates
};
```
