### ISSUE TITLE
Select an entire week

### ISSUE THREAD

**Issue by rgbskills** [crsten/datepickk#8]
I would like the user to be able to select single, multiple, or an entire week. is there any way to do that?

similar to this: http://jsfiddle.net/manishma/AVZJh/light/ but I will need every date in the week in JSON.

**Comment by crsten** [comment]
There is no built in function to handle this at the moment. But you can do it manually meanwhile like this:

```js
let datepicker = new Datepickk({
	range: true,
	onSelect: function(checked) {
		let date = moment(this);
		datepicker.unselectAll(true);
		datepicker.selectDate(date.startOf('week').toDate(), true);
		datepicker.selectDate(date.endOf('week').toDate(), true);
	}
});
datepicker.show();
```
With this solution you are basically able to select whatever range you want.
Be aware that my solution is depending on [moment](http://momentjs.com/).

**Comment by rgbskills** [comment]
That works :) Thank you
