### ISSUE TITLE
Date format for 'selectedDates'

### ISSUE THREAD

**Issue by rgbskills** [crsten/datepickk#9]
I would like to change the `selectedDates` output to be a simple date, right now I get an array with dates in this format `2017-02-14T22:00:00.000Z` and I would like to get only the date like this `2017-02-14` is there any way that this can be achieved ?

**Comment by crsten** [comment]
Yes the returned dates are [Javascript Dates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date). In your case i would recommend [momentjs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)

Then you can get the requested format like this:

```js
var output = moment(YOUR_DATE).format('YYYY-MM-DD')
```

**Comment by rgbskills** [comment]
Thank you, I really love datepickk. Keep up the good work :)
